version: '3.9'

services:

  rest_hol3_service:
    restart: always
    container_name: rest_hol3_service_container
    build: .
    ports:
      - 1000:1000
    volumes:
      - .:/app
    networks: 
      - service_hol3_demo

networks:
  service_hol3_demo:
    name: net_service_hol3_demo